# AVA CORE™ Netlify Deployment Configuration
# Copyright © 2025 Ervin Remus Radosavlevici. All Rights Reserved.
# Watermark: radosavlevici210@icloud.com

[build]
  publish = "."
  command = "echo 'AVA CORE Enterprise Deployment'"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

# Headers for security and legal compliance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.socket.io https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
    X-Copyright = "Copyright © 2025 Ervin Remus Radosavlevici. All Rights Reserved."
    X-Watermark = "radosavlevici210@icloud.com"
    X-Legal-Notice = "Protected by NDA and Enterprise License Agreement"
    X-Authorized-Users = "radosavlevici210@icloud.com, ervin210@icloud.com"

# Legal documentation headers
[[headers]]
  for = "/legal"
  [headers.values]
    X-Legal-Framework = "Enterprise Compliance Active"
    X-NDA-Required = "true"
    X-License-Type = "Proprietary Enterprise"

# API security headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-API-Protection = "Enterprise Security Active"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Manifest and service worker
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=86400"