# Netlify Configuration for AVA CORE™ Neural AI Assistant
# Copyright © 2025 Ervin Remus Radosavlevici
# Enterprise Production Deployment

[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"

# Production redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for enterprise deployment
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.socket.io https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' wss: ws:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Enterprise watermark and copyright protection
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Copyright = "Ervin Remus Radosavlevici"
    X-Watermark = "radosavlevici210@icloud.com"
    X-Enterprise-System = "AVA-CORE"
    X-Timestamp = "2025-06-05T12:15:00Z"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  ENTERPRISE_MODE = "true"
  COPYRIGHT_OWNER = "Ervin Remus Radosavlevici"
  WATERMARK = "radosavlevici210@icloud.com"
  AUTHORIZED_CONTACT = "ervin210@icloud.com"

# Development environment
[context.deploy-preview.environment]
  NODE_ENV = "development"
  ENTERPRISE_MODE = "true"

# Branch deploys
[context.branch-deploy.environment]
  NODE_ENV = "staging"
  ENTERPRISE_MODE = "true"