modules = ["python-3.11"]

[workflows]
runButton = "Project"

[[workflows.workflow]]
name = "Project"
mode = "parallel"
author = "radosavlevici210@icloud.com"

[[workflows.workflow.tasks]]
task = "workflow.run"
args = "AVA CORE Server"

[[workflows.workflow]]
name = "AVA CORE Server"
author = "radosavlevici210@icloud.com"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "python app.py"
waitForPort = 5000

[deployment]
run = ["sh", "-c", "python app.py"]

[[ports]]
localPort = 5000
externalPort = 80